
# Запрос для фильтрации фильмов по режиссёрам, начинающимся на букву "C"
PREFIX imdb: <http://academy.ontotext.com/imdb/>
PREFIX schema: <http://schema.org/>

SELECT ?movie ?movieName ?directorName
WHERE {
  ?movie schema:name ?movieName ;
         schema:director ?director .
  ?director schema:name ?directorName .
  
  FILTER STRSTARTS(?directorName, "C")
}
ORDER BY ?directorName
